[REVIEW][FEATURE][UWANG-165] - Card user information(detail)
Bluhabit/uwang-admin-fe pull request #11
Opened 2024-02-23 16:12 UTC by fahmi-azzuhri

[REVIEW][FEATURE][UWANG-165] - Card user information(detail)

#### Description

> Description of features, bugs, improvements or any changes in this MR.

#### Ticket Reference(s)

[UWANG-165](https://bluehabit.atlassian.net/browse/UWANG-165)

#### Validation

##### UI Changes

> Screenshot or video of UI-related changes
![localhost-3000](https://github.com/Bluhabit/uwang-admin-fe/assets/91070416/3a58888e-a307-43ca-9736-6fa73ecbda1e)

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> Mention other user or extra note unrelated to the MR here.

2024-02-27 13:11 UTC, triandamai requested changes
benerin dulu @fahmi-azzuhri

2024-02-27 13:11 UTC, triandamai commented on components/UserInformation.vue
> +export default defineComponent({
gausah pake `defineComponent` pake syntax sugar aja `<script setup lang="ts">` @fahmi-azzuhri

2024-02-27 13:11 UTC, triandamai commented on components/UserInformation.vue
> +            birthDate: new Date('1990-01-01'),
pake `ref` @fahmi-azzuhri

2024-02-27 13:11 UTC, triandamai commented on components/UserInformation.vue
> +        userName(): string {
ga perlu computed ya kalo udah pake ref

2024-02-27 15:04 UTC, fahmi-azzuhri commented
done bang @triandamai

2024-02-29 10:47 UTC, triandamai approved these changes

2024-02-29 10:47 UTC, merged