[REVIEW][FEATURE][UWANG-156] - Create Main Layout With Sidebar
Bluhabit/uwang-admin-fe pull request #12
Opened 2024-02-24 15:08 UTC by maulanafikriash

#### Description

> Description of features, improvements design.

#### Ticket Reference(s)

[UWANG-156](https://bluehabit.atlassian.net/browse/UWANG-156)

#### Validation

##### UI Changes

> Screenshot or video of UI-related changes
![mainlay-ss](https://github.com/Bluhabit/uwang-admin-fe/assets/112919641/0614942f-b520-42c7-854f-0850f4ed8e6d)

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> Mention other user or extra note unrelated to the MR here.
@triandamai

2024-02-27 06:57 UTC, azkifairuz commented
data tablenya udah ada, pull dri feature/UWANG-159

2024-02-27 09:49 UTC, maulanafikriash commented
> data tablenya udah ada, pull dri feature/UWANG-159

Oke sip

2024-02-27 13:13 UTC, triandamai requested changes
cek dulu ya

2024-02-27 13:13 UTC, triandamai commented on components/MainLayout.vue
> +            <!-- <StatisticDashboard :statistic="dataStatistic" />
klo unused di hapus aja @maulanafikriash

2024-02-27 13:13 UTC, triandamai commented on components/MainLayout.vue
> +      <!-- <Sidebar/> -->
di bikin `slot` ya

2024-02-27 14:42 UTC, maulanafikriash commented on components/MainLayout.vue
> +      <!-- <Sidebar/> -->
Oke udah solved mas

2024-02-29 10:48 UTC, triandamai approved these changes

2024-02-29 10:48 UTC, merged