[REVIEW][FEATURE][UWANG-161] - integration statistic card
Bluhabit/uwang-admin-fe pull request #15
Opened 2024-03-04 05:44 UTC by maulanafikriash

#### Description

> Description of features, improvements design.

#### Ticket Reference(s)

[UWANG-161](https://bluehabit.atlassian.net/browse/UWANG-161)

#### Validation

##### UI Changes

> Screenshot or video of UI-related changes

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> Mention other user or extra note unrelated to the MR here.
@triandamai

2024-03-05 13:49 UTC, triandamai commented on components/StatisticCard.vue
>    console.log("up",statistic);
hapus ya @maulanafikriash

2024-03-05 13:49 UTC, triandamai commented on pages/preview.vue
> +import { useUserStatisticsStore } from '~/store/getStatisticCard';
gaperlu import @maulanafikriash nuxt udah otomatis import

2024-03-05 13:49 UTC, triandamai commented on store/getStatisticCard.ts
> +        const response = await fetch('https://api.bluhabit.id/account/v1/admin/get-statistic');
pake `useApi` ya @maulanafikriash

2024-03-05 13:50 UTC, triandamai commented on store/getStatisticCard.ts
> +        console.error('Error fetching statistics:', error);
remove ya @maulanafikriash

2024-03-05 13:50 UTC, triandamai requested changes
update dulu ya

2024-03-05 14:28 UTC, maulanafikriash commented on store/getStatisticCard.ts
> +        console.error('Error fetching statistics:', error);
oke sudah mas @triandamai

2024-03-05 14:30 UTC, triandamai commented on store/getStatisticCard.ts
> +        const api = useApi();
```javascript
const {get} = useApi()
const data = await get<StatisticResponse>("/<url>")
```
ps: `StatisticResponse` bikin di file `type.ts`, `url` cukup endpoint aja `https//.api.bluhabit.id` nya gausah

2024-03-05 14:30 UTC, triandamai commented on store/getStatisticCard.ts
> +interface StatisticData {
pindah ke `type.ts`

2024-03-05 14:30 UTC, triandamai requested changes
cek ya

2024-03-05 15:30 UTC, triandamai commented on store/getStatisticCard.ts
>  export const useUserStatisticsStore = defineStore('getStatisticsCard', {
`defineStore<string,{statistics:StatisticData,isLoading:boolean}>(...)`

2024-03-05 15:31 UTC, triandamai requested changes
cek

2024-03-05 15:34 UTC, triandamai commented on store/getStatisticCard.ts
>  export const useUserStatisticsStore = defineStore('getStatisticsCard', {
export const useStatistic = defineStore("statistic",....

2024-03-06 03:09 UTC, maulanafikriash commented on store/getStatisticCard.ts
>  export const useUserStatisticsStore = defineStore('getStatisticsCard', {
dah ku ubah, dicek lagi mas @triandamai

2024-03-16 10:45 UTC, triandamai requested changes
revisi dikit @maulanafikriash

2024-03-16 10:45 UTC, triandamai commented on store/getStatisticCard.ts
> +import type { StatisticData } from "~/type/statisticData";
nama store nya ganti `useStatistic` @maulanafikriash

2024-03-16 10:45 UTC, triandamai commented on store/getStatisticCard.ts
> +        const { data } = await get<StatisticResponse>('https://api.bluhabit.id/uwang/dev/account/v1/admin/get-statistic');
ga perlu full url ya kan udah di set base urlnya @maulanafikriash

2024-03-16 10:45 UTC, triandamai commented on store/getStatisticCard.ts
> +  state: () => ({
kalo mau ada type nya gausah pake `as` tapi:
```typescript
const useStatistic = defineStore<string,{/* ini type state*/},{/* ini type buat getter */},{/* ini type action */}>('statistic',{
    state:()=>({})// ini bakal sesuai dengan type yang uda di define
})
```

2024-03-16 10:45 UTC, triandamai commented on store/getStatisticCard.ts
> +      active_user: 0,
pake `camelCase` ya `snake_case` hanya di pakai untuk pertukaran data api

2024-03-16 10:45 UTC, triandamai commented on store/getStatisticCard.ts
> +      try {
gausah pake try catch karena bakal susah debugging kalo ada error

2024-03-17 00:47 UTC, maulanafikriash commented on store/getStatisticCard.ts
> +      try {
OKe dah ku ubah mas @triandamai

2024-03-17 09:50 UTC, triandamai requested changes
last @maulanafikriash

2024-03-17 09:50 UTC, triandamai commented on pages/preview.vue
> +import { useStatistic } from '~/store/useStatistic';
ga perlu import ya @maulanafikriash udah otomatis dari nuxt

2024-03-17 11:00 UTC, maulanafikriash commented on pages/preview.vue
> +import { useStatistic } from '~/store/useStatistic';
error tapi mas, apa biarin aja ? @triandamai

2024-03-19 14:04 UTC, triandamai commented on pages/preview.vue
> +import { useStatistic } from '~/store/useStatistic';
itu warning dari intellisense aja

2024-03-19 14:06 UTC, maulanafikriash commented on pages/preview.vue
> +import { useStatistic } from '~/store/useStatistic';
oke sip mas @triandamai

2024-03-19 14:12 UTC, maulanafikriash commented on pages/preview.vue
> +import { useStatistic } from '~/store/useStatistic';
dah ku remove mas importnya @triandamai

2024-03-19 14:34 UTC, triandamai requested changes
di integrasiin ke pages/dashboard ya

2024-03-19 14:34 UTC, triandamai commented
@maulanafikriash

2024-03-19 15:54 UTC, maulanafikriash commented
Oke udah mas di integrasiin ke pages/main/dashboard @triandamai

2024-03-25 19:12 UTC, merged