[REVIEW][FEATURE][UWANG-170] - Integration signin admin
Bluhabit/uwang-admin-fe pull request #16
Opened 2024-03-05 14:21 UTC by fahmi-azzuhri

[REVIEW][FEATURE][UWANG-170] - Integration signin admin

#### Description

> Description of features, bugs, improvements or any changes in this MR.

#### Ticket Reference(s)

[UWANG-170](https://bluehabit.atlassian.net/browse/UWANG-170)

#### Validation

##### UI Changes

> Screenshot or video of UI-related changes

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> Mention other user or extra note unrelated to the MR here.

2024-03-05 15:44 UTC, triandamai commented on components/SigninForm.vue
> +import { useAuth } from '../store/useAuth'
gausah pake import ya

2024-03-05 15:51 UTC, triandamai commented on components/SigninForm.vue
> +    await signIn(email.value, password.value)
pake function aja ya

2024-03-05 15:51 UTC, triandamai commented on store/useAuth.ts
> +export const useAuth = defineStore('auth', {
user nya di bikin type terpisah aja @fahmi-azzuhri

2024-03-05 15:52 UTC, triandamai commented on store/useAuth.ts
> +      try {
gausah pake try catch ya

2024-03-05 15:52 UTC, triandamai commented on store/useAuth.ts
> +        const response = await fetch('https://api.bluhabit.id/auth/v1/admin/sign-in', {
pake useApi ya

2024-03-05 15:52 UTC, triandamai requested changes
cek

2024-03-05 17:06 UTC, fahmi-azzuhri commented
done bang, tolong di cek @triandamai

2024-03-16 10:52 UTC, triandamai requested changes
repisi @fahmi-azzuhri

2024-03-16 10:52 UTC, triandamai commented on components/SigninForm.vue
> +const handleSubmit = () => {
pake keyword `function` ya `const,let,var` kita khususin buat variabel aja @fahmi-azzuhri

2024-03-16 10:52 UTC, triandamai commented on store/useAuth.ts
> +    user: {} as UserResponse,
type nya jangan pake as ya tapi `defineStore<string,{},{},{}>(...)`

2024-03-16 10:52 UTC, triandamai commented on store/useAuth.ts
> +    signIn(email: string, password: string) {
pake keyword `async ya`

2024-03-16 10:52 UTC, triandamai commented on store/useAuth.ts
> +      const signInRequest = post<{ token: string; user: any }>('auth/v1/admin/sign-in', {
pakein type ya

2024-03-16 10:52 UTC, triandamai commented on store/useAuth.ts
> +      signInRequest.then((response) => {
langsung aja `const response = await post<UserResponse>('/...',{})`

2024-03-16 10:52 UTC, triandamai commented on store/useAuth.ts
> +            console.log('Sign in successful');
jangan lupa console.log di hapus ya

2024-03-16 10:52 UTC, triandamai commented on store/useAuth.ts
> +        if (response.isSuccessful) {
coba pake metode `guard clause` 
misal

```typescript
if(!response.isSuccesfull) {
  //todo

  return /*memastikan kode berenti disini*/
}

//kode ini di eksekusi sudah dijamin isSuccesfull == true
if(!response.data){
 //todo  
 return
}
//kode ini di eksekusi sudah dijamin if(data)

...
```

2024-03-16 10:52 UTC, triandamai commented on store/useAuth.ts
> +      signInRequest.catch((error) => {
ga perlu catch ya udah di handle di `useApi`

2024-03-16 15:45 UTC, fahmi-azzuhri commented
di SigninForm.vue

const {signIn} = useAuth()

kenapa error mulu ya bang @triandamai

2024-03-17 09:53 UTC, triandamai commented
boleh di attach errornya ga @fahmi-azzuhri ?

2024-03-17 09:53 UTC, triandamai approved these changes

2024-03-17 12:57 UTC, fahmi-azzuhri commented
Property 'signIn' does not exist on type '_StoreWithState<string, { token: string; user: UserResponse; isLoggedIn: boolean; errorMessage: string; }, {}, {}> & { token: string; user: any; isLoggedIn: boolean; errorMessage: string; } & _StoreWithGetters<...> & PiniaCustomProperties<...> & PiniaCustomStateProperties<...>'

2024-03-19 14:07 UTC, triandamai commented
Conflict @fahmi-azzuhri 
itu error karena di defineStore nya ga di define type action nya

`defineStore<string,{/*ini type state*/},{/* ini type getter */},{/* ini type action */}`

2024-03-19 14:16 UTC, triandamai commented
integrasi sekalian bikin page nya ya @fahmi-azzuhri

2024-03-29 20:09 UTC, azkifairuz approved these changes
nice

2024-03-29 20:09 UTC, merged