[REVIEW][FEATURE][UWANG-215] - Access Management Screen
Bluhabit/uwang-admin-fe pull request #18
Opened 2024-03-15 14:13 UTC by fahmi-azzuhri

#### Description

> create access management screen

#### Ticket Reference(s)

[UWANG-215](https://bluehabit.atlassian.net/browse/UWANG-215)

#### Validation

##### UI Changes

> Screenshot or video of UI-related changes
![Screenshot 2024-03-15 211137](https://github.com/Bluhabit/uwang-admin-fe/assets/91070416/a9ac42a0-6674-487f-ac77-aa824d5bcf89)

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> Mention other user or extra note unrelated to the MR here.

[UWANG-215]: https://bluehabit.atlassian.net/browse/UWANG-215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-03-16 10:57 UTC, triandamai requested changes
ini buat halaman access managemen kan ? @maulanafikriash 
kalau iya dibikin di `pages/access-management/index.vue`

2024-03-16 10:57 UTC, triandamai commented on components/TableRole.vue
> +            <table class="min-w-full divide-y divide-gray-200">
pake component `DataTable` ya [DataTable](https://github.com/Bluhabit/uwang-admin-fe/blob/development/components/DataTable.vue)

2024-03-16 13:02 UTC, fahmi-azzuhri commented on components/TableRole.vue
> +            <table class="min-w-full divide-y divide-gray-200">
ok bang w pindahin dulu

2024-03-17 09:55 UTC, triandamai approved these changes

2024-03-17 09:56 UTC, merged