[REVIEW][FEATURE][UWANG-217]  - Create component alert success
Bluhabit/uwang-admin-fe pull request #19
Opened 2024-03-17 01:54 UTC by maulanafikriash

#### Description

> Description of features, improvements design.

#### Ticket Reference(s)

[UWANG-217](https://bluehabit.atlassian.net/browse/UWANG-217)

#### Validation

##### UI Changes

> Screenshot or video of UI-related changes
![ss-alert](https://github.com/Bluhabit/uwang-admin-fe/assets/112919641/9b65523b-3af3-4bb2-9921-f3ae11b14492)

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> Mention other user or extra note unrelated to the MR here.
mas @triandamai

2024-03-17 09:56 UTC, triandamai requested changes
tes

2024-03-17 09:56 UTC, triandamai commented on components/AlertSuccess.vue
> +<template>
udah di coba di tepel di screen nya blm? @maulanafikriash

2024-03-17 10:41 UTC, maulanafikriash commented on components/AlertSuccess.vue
> +<template>
udah mas di preview @triandamai

2024-03-19 14:09 UTC, triandamai approved these changes

2024-03-19 14:09 UTC, merged