[REVIEW][FEATURE][UWANG-216] - Component Modal add access
Bluhabit/uwang-admin-fe pull request #21
Opened 2024-03-20 13:35 UTC by fahmi-azzuhri

#### Description

> Description of features, bugs, improvements or any changes in this MR.

#### Ticket Reference(s)

[UWANG-216](https://bluehabit.atlassian.net/browse/UWANG-216)

#### Validation

##### UI Changes

> Screenshot or video of UI-related changes
![Screenshot 2024-03-19 234439](https://github.com/Bluhabit/uwang-admin-fe/assets/91070416/5f2712ae-228d-40e7-a33e-62d27111ade6)

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> Mention other user or extra note unrelated to the MR here.

2024-03-20 13:35 UTC, fahmi-azzuhri commented
kalo buat autocomplete itu dia mesti pake library tambahan ga si bang @triandamai

2024-03-22 22:51 UTC, azkifairuz commented on components/ModalAccess.vue
> +const users = ['triandamai', 'fahmiazzuhri', 'fikrimaulana'];
ininya dibikin jadi props aja, nnti kan si modal mau dipake di screen dan sumber list usernya nnti kan dari api, nah sebaiknya get apinya dri screen, nnti data nya baru dikirim ke komponent lewat props

2024-03-25 18:50 UTC, azkifairuz requested changes
punten

2024-03-25 18:50 UTC, azkifairuz commented on components/ModalAccess.vue
> +    onClose: () => void;
onclose kenapa g emmit aja mi, kalo props buat data, klo emmit buat function handle handle

2024-03-25 18:50 UTC, azkifairuz commented on pages/access-management/index.vue
> +    const response = await api.get<UserCredentialResponse[]>('/uwang/dev/account/v1/admin/get-list-user');
sorry mi llupa gua, api nya bukan get-list-user, tapi nnti api nya search-user-by-username
bisa cek https://uwang-docs.vercel.app/admin/access-management#search-user-by-username

2024-03-25 18:50 UTC, azkifairuz commented on components/ModalAccess.vue
> +
bikkin emmit buat handle button cancle sama tambahkan ya mi

2024-03-26 13:30 UTC, fahmi-azzuhri commented on pages/access-management/index.vue
> +    const response = await api.get<UserCredentialResponse[]>('/uwang/dev/account/v1/admin/get-list-user');
ngoghey ki

2024-03-26 21:08 UTC, azkifairuz approved these changes
mantapppp

2024-03-26 21:08 UTC, merged