[REVIEW][FEATURE][UWANG-160] - Create Sidebar Component
Bluhabit/uwang-admin-fe pull request #7
Opened 2024-02-22 18:09 UTC by maulanafikriash

#### Description

> Description of features, improvements design.

#### Ticket Reference(s)

[UWANG-160](https://bluehabit.atlassian.net/browse/UWANG-160)

#### Validation

##### UI Changes

![sidebar-uwang](https://github.com/Bluhabit/uwang-admin-fe/assets/112919641/cf2b2cdf-5fa1-46c3-9adb-89b8e65e6bf5)

##### Coverage

> Test coverage screenshot.

N/A

#### Note(s)

> Mention other user or extra note unrelated to the MR here.
@triandamai

2024-02-27 13:07 UTC, triandamai requested changes
cek ya @maulanafikriash

2024-02-27 14:22 UTC, maulanafikriash commented on components/Sidebar.vue
> +export default {
Sip udah ku ganti mas @triandamai

2024-02-29 10:46 UTC, triandamai commented on components/Sidebar.vue
> +export default {
conflict @maulanafikriash

2024-02-29 10:58 UTC, maulanafikriash commented on components/Sidebar.vue
> +export default {
oke udah ku fix mas @triandamai

2024-03-03 03:35 UTC, triandamai approved these changes

2024-03-03 03:35 UTC, merged